Update from head branch, svn revision 281954.

diff --git a/etc/rc.d/hostid_save b/etc/rc.d/hostid_save
--- a/etc/rc.d/hostid_save
+++ b/etc/rc.d/hostid_save
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $FreeBSD: head/etc/rc.d/hostid_save 208307 2010-05-19 19:03:19Z dougb $
+# $FreeBSD: head/etc/rc.d/hostid_save 281565 2015-04-15 21:48:06Z delphij $
 #
 
 # PROVIDE: hostid_save
@@ -16,11 +16,18 @@ rcvar="hostid_enable"
 
 hostid_save()
 {
-	if [ ! -r ${hostid_file} ]; then
-		$SYSCTL_N kern.hostuuid > ${hostid_file}
-		if [ $? -ne 0 ]; then
-			warn "could not store hostuuid in ${hostid_file}."
+	current_hostid=`$SYSCTL_N kern.hostuuid`
+
+	if [ -r ${hostid_file} ]; then
+		read saved_hostid < ${hostid_file}
+		if [ ${saved_hostid} = ${current_hostid} ]; then
+			exit 0
 		fi
+	fi
+
+	echo ${current_hostid} > ${hostid_file}
+	if [ $? -ne 0 ]; then
+		warn "could not store hostuuid in ${hostid_file}."
 	fi
 }
 
